type ColorTypes = {
    darthVaderBlack: string,
    lightsaberBlue: string,
    sithRed: string,
    falconGrey: string,
    endorGreen: string,
    jediRobeBrown: string,
    nabooYellow: string,
    saberSilver: string,
    padmePurple: string,
    coruscantSkyline: string,
    resistanceRed: string,
    starkillerWhite: string,
    kyloRenBlack: string,
    reysStaffBrown: string,
    ahchToBlue: string,
    imperialWhite: string,
    tieFighterGrey: string,
    deathStarSilver: string,
    stormtrooperArmor: string,
    royalGuardRed: string,
};

const Colors: ColorTypes = {
    darthVaderBlack: '#0b0b0b',
    lightsaberBlue: '#0291d9',
    sithRed: '#d90012',
    falconGrey: '#8c8c8c',
    endorGreen: '#3d6d4b',
    jediRobeBrown: '#5a4f3f',
    nabooYellow: '#f9c901',
    saberSilver: '#c0c0c0',
    padmePurple: '#755c8b',
    coruscantSkyline: '#2e2e2e',
    resistanceRed: '#ca1f1b',
    starkillerWhite: '#f0f0f0',
    kyloRenBlack: '#1a1a1a',
    reysStaffBrown: '#9b7e46',
    ahchToBlue: '#4bacc6',
    imperialWhite: '#ffffff',
    tieFighterGrey: '#545454',
    deathStarSilver: '#a5a5a5',
    stormtrooperArmor: '#f8f8f8',
    royalGuardRed: '#aa0000',
};

export default Colors